import json
from pydantic import BaseModel

class SemanticPromptBuilder:
    PROMPT_VERSION = "v1.0"

    @classmethod
    def build_table_enrichment_prompt(cls, business_context_json: str) -> str:
        """
        Builds a deterministic prompt asking the LLM to generate semantic layer
        definitions (Dimensions, Measures, KPIs, Glossary, Relationships) for a table.
        """
        prompt = f"""
You are an Enterprise Data Architect and AI Semantic Generator.
Your objective is to enrich a metadata catalog by generating a logical Business Semantic Layer.

Below is the structured metadata context for a single database table. It includes the physical table name, column names, data types, statistical profiles (e.g., distinct counts, min, max), and known foreign key relationships.

CONTEXT:
{business_context_json}

INSTRUCTIONS:
1. Analyze the context and determine the primary business purpose of this table.
2. Generate Dimensions: Identify categorical columns (e.g., status, type, category).
3. Generate Measures: Identify raw numeric columns that can be aggregated (e.g., amount, quantity).
4. Generate KPIs (Metrics): Propose derived calculations combining physical columns (e.g., SUM(revenue) - SUM(cost)).
5. Generate Business Glossary Terms: Identify domain-specific terms and provide clear business definitions.
6. Generate Relationships: Map outbound and inbound foreign keys into business-readable semantic relationships.
7. Assess Confidence: Provide a confidence score between 0.0 and 1.0 representing how confident you are in these semantic derivations.

CRITICAL RULES:
- DO NOT invent, hallucinate, or assume any physical table names or column names that are not present in the CONTEXT.
- If an expression for a KPI uses columns, they MUST be exact matches to the physical column names.
- Ensure 'is_time_dimension' is true only for timestamp/date columns.
- DO NOT generate SQL queries, only valid expressions for KPIs.

Output strictly valid JSON conforming to the requested schema.
"""
        return prompt.strip()

    @classmethod
    def build_global_enrichment_prompt(cls, global_context_json: str) -> str:
        """
        Builds a deterministic prompt asking the LLM to generate global semantic layer
        definitions (Ontology, Dashboards, Questions, Context, cross-table KPIs) for the entire database.
        """
        prompt = f"""
You are an Enterprise Data Architect and AI Semantic Generator.
Your objective is to enrich a metadata catalog by generating a logical Business Semantic Layer for an entire database.

Below is the global database context. It includes table names, table descriptions (already generated by AI), and key relationships (primary and foreign keys).

CONTEXT:
{global_context_json}

INSTRUCTIONS:
1. Analyze the context and determine the primary business purpose of this entire database (AI Context).
2. Generate Business Ontology: Group tables into logical business domains (e.g., 'Sales', 'HR', 'Inventory').
3. Generate Cross-Table KPIs: Propose metrics that span multiple tables (e.g., Revenue per Customer).
4. Generate Dashboard Recommendations: Propose logical groupings of KPIs into Dashboards for end users.
5. Generate Suggested Questions: Propose natural language questions a business user might ask of this data.
6. Assess Confidence: Provide a confidence score between 0.0 and 1.0 representing how confident you are.

CRITICAL RULES:
- DO NOT invent, hallucinate, or assume any physical table names or column names that are not present in the CONTEXT.
- Output strictly valid JSON conforming to the requested schema.
"""
        return prompt.strip()

    @classmethod
    def build_query_planner_prompt(cls, intent_json: str, metric_ctx: str, dim_ctx: str, ai_context_payload: str) -> str:
        """
        Builds the deterministic prompt for the Enterprise Query Planner.
        It enforces strict name adherence and Logical Query Plan JSON output.
        """
        prompt = f"""
You are the Enterprise Query Planner for an Advanced Conversational Analytics Engine.
Generate a strictly typed PlannerLLMOutput using ONLY the provided Dimension, Metric, and KPI Names. 
Do NOT invent columns, tables, or names. Do NOT generate executable SQL.

USER INTENT:
{intent_json}

RESOLVED SEMANTIC CONTEXT:
[METRICS & KPIs]
{metric_ctx}

[DIMENSIONS]
{dim_ctx}

GLOBAL AI CONTEXT & TIME INTELLIGENCE:
{ai_context_payload}

Instructions:
1. Map the intent metric/kpi to the provided Names. Output as a list of strings in 'metric_names' or 'kpi_names'.
2. Map the intent dimensions to the provided Dimension Names. Output as a list of strings in 'dimension_names'. DO NOT include time units (Month, Year, etc) as dimensions; use the 'time_granularity' field for that.
3. Apply filters using the correct operators. Use Dimension Names for the 'column_name' if filtering by a dimension.
4. Apply 'time_intelligence' logic according to the Global AI Context (e.g. YTD calculations).
5. Recommend a suitable chart type in 'chart_recommendation' (e.g., bar_chart, line_chart).
6. DO NOT invent Names. Only use those provided in the context to minimize hallucinations and enforce semantic integrity.
7. Provide a 'confidence_score' (0.0 to 1.0) and a brief 'reasoning' for your plan.
"""
        return prompt.strip()
